### ISSUE TITLE
_fs2.default.existsSync is not a function

### ISSUE THREAD

**Issue by mauroporrasp** [babel/babel-standalone#64]
If I go back to 6.14.0 it works.

The error:
![screenshot from 2016-10-25 18-25-20](https://cloud.githubusercontent.com/assets/167700/19707916/7f67a81c-9ae0-11e6-9096-217930d96384.png)

My code:
![screenshot from 2016-10-25 18-25-41](https://cloud.githubusercontent.com/assets/167700/19707917/7f6976d8-9ae0-11e6-98a0-b9680e2ee245.png)

**Comment by Daniel15** [comment]
Interesting, I can't reproduce the issue in the [Babel REPL](https://babeljs.io/repl/), which uses babel-standalone.

**Comment by mauroporrasp** [comment]
I'm using Ubuntu Linux + Chrome Version 52.0.2743.82 (64-bit)

**Comment by ConnorAtherton** [comment]
This looks related to this issue https://github.com/babel/babel/issues/4778 caused by this commit https://github.com/babel/babel/pull/4731/files.

**Comment by Daniel15** [comment]
Ah I see, it only happens when using inline `<script>` tags. Looking into it.

**Comment by Daniel15** [comment]
Published 6.18.1 to fix this. Thanks for reporting!
