### ISSUE TITLE
Invalid preset specified in Babel options: "stage2"

### ISSUE THREAD

**Issue by miclaus** [babel/babel-standalone#66]
When I insert a babel script with the `data-presets` attribute according to the `README`:
```
  <script type="text/babel" src="assets/js/app.js" data-presets="es2015,stage2"></script>  
```

I get the following error:
```
  babel.min.js:1 Uncaught Error: Invalid preset specified in Babel options: "stage2"  
```

**Comment by loganfsmyth** [comment]
That should be `stage-2` most likely.

**Comment by Daniel15** [comment]
Yeah, `stage-2`... Feel free to send a pull request updating the readme if you like :)

**Comment by miclaus** [comment]
Thanks !

@Daniel15 sure will do this afternoon :)

**Comment by miclaus** [comment]
There you go :)

https://github.com/babel/babel-standalone/pull/67

**Comment by Daniel15** [comment]
Thanks! 😄
