### ISSUE TITLE
Include babili in cdnjs?

### ISSUE THREAD

**Issue by jarben** [babel/babel-standalone#68]
Is it possible to include babili.min.js in the https://cdnjs.com/libraries/babel-standalone build?

**Comment by Daniel15** [comment]
Sure, I'll do it :) For now you can use https://unpkg.com/ :)

**Comment by jarben** [comment]
Didn't know about unpkg, thanks for sharing! Cool looking forward when it's part of cdnjs, thanks Daniel!

**Comment by Daniel15** [comment]
https://github.com/cdnjs/cdnjs/pull/9696 adds it to CDNJS 👍

**Comment by Daniel15** [comment]
It's up now! https://cdnjs.cloudflare.com/ajax/libs/babili-standalone/0.0.8/babili.min.js

**Comment by jarben** [comment]
Awesome, thanks heaps Daniel!
