### ISSUE TITLE
Require is not supported in the browser..

### ISSUE THREAD

**Issue by jonysy** [babel/babel-standalone#71]
Full message:

```
Require is not supported in the browser, you need a commonjs environment such as node.js/io.js, browserify/webpack etc
```

What needs to be done to get this to work?

```
import { foo } from "./bar";
```

**Comment by loganfsmyth** [comment]
You cannot use `babel-standalone` in this case. `babel-standalone` is able to compile individual files, but it has no support for modular code. For modules to work, you would need to use a normal Babel workflow using something like Webpack or Browserify to bundle all of your files into a single file to execute in the browser.

**Comment by jonysy** [comment]
Thank you, Logan :)
