### ISSUE TITLE
Support link preload to fix browsers that prevent fetching scripts with an invalid type attribute

### ISSUE THREAD

**Issue by cryptoquick** [babel/babel-standalone#72]
When using the following syntax:

```html
  <script type="text/babel" src="src/main.js"></script>
```

On Chrome 55, the console displays this error:

`Fetching scripts with an invalid type/language attributes is deprecated and will be removed in M56, around January 2017. See https://www.chromestatus.com/features/5760718284521472 for more details.`

There are more details here: https://www.chromestatus.com/feature/5760718284521472

The suggested approach is to use link preload, which I presume would be something like this:

```html
  <link rel="preload" href="src/main.js" as="script" data-babel="es2015,stage-3">
```

**Comment by Daniel15** [comment]
I don't think the notice is relevant for babel-standalone. Since it loads the script using XMLHttpRequest: (see https://github.com/babel/babel-standalone/blob/master/src/transformScriptTags.js#L75), we're not actually relying on the browser to preload the script.

**Comment by yash2code** [comment]
@cryptoquick  the suggested approach not working !

**Comment by Daniel15** [comment]
This is not relevant to babel-standalone, as we don't rely on preloading. Babel-standalone is still working on Chrome 56. Closing this issue.
