### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by taion** [babel/babel-standalone#73]
Could you cut a new release with an updated `debug` dependency version?

There was an issue with the browser build of visionmedia/debug v2.4.5 that made the browser build of debug not work outside of browsers (https://github.com/visionmedia/debug/commit/1c625d45786fa8b3f0d285d3165e4dd346985fac#diff-de1a5a7de991855714cdf433e9f8be96R13, fixed in https://github.com/visionmedia/debug/commit/fb6e43d66bcb7515424ffec3121aa60c790826b8#diff-b056c1ad802eb5041886154caaf3a3d4R13).

It's fixed in v2.5.1. As the npm release exposes a bundled build, I can't get this fix just by reinstalling.

**Comment by Daniel15** [comment]
I'm current on vacation but I'll try to cut a release soon. In the
meantime, feel free to clone the repo and build it yourself :)

**Comment by Daniel15** [comment]
6.21.1 was released 10 days ago.

**Comment by taion** [comment]
Thanks!

**Comment by Daniel15** [comment]
Sorry for the delay in closing this issue - I forgot about it until just now when I was looking through my projects for stale issues 😃
