### ISSUE TITLE
babili-standalone requires ES6

### ISSUE THREAD

**Issue by fatcerberus** [babel/babel-standalone#75]
I'm currently using babel-standalone in the compiler for my game engine [minisphere](https://github.com/fatcerberus/minisphere).  I use [Duktape](https://github.com/svaarala/duktape) as my JavaScript backend, which currently only supports ES5.1 with a few select ES6 features, so I need a transpiler.  Babel itself works fine in this environment, but Babili does not, as it seems to require at least ES6 `Set`.  Could Babili be made to run in ES5 environments?

**Comment by hzoo** [comment]
fyi Babili dropped node 0.10/0.12 support from the beginning, and Babel will soon too

**Comment by fatcerberus** [comment]
I'm not using it in Node.js though... that's why I need the standalone version.

**Comment by Daniel15** [comment]
Hi @fatcerberus! If the only thing missing is ES6 `Set`, then you can try loading an ES6 polyfill (such as the Babel polyfill: https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.20.0/polyfill.js, or core-js) and see if that helps. Let me know how you go 😃 

@hzoo - Babel-standalone is designed for non-Node.js environments, so Node.js version isn't too relevant. It's just relevant in that Babel may rely on things that are in Node.js 4+, but the babel-standalone build uses Babel to compile Babel itself to ES5 for older engines.

**Comment by fatcerberus** [comment]
> the babel-standalone build uses Babel to compile Babel itself to ES5 for older engines.

Hm, I guess transpilation alone can't do much about built-ins, only syntax.  I'll try the polyfill and let you know what happens, thanks.

**Comment by Daniel15** [comment]
Yeah, for builtins, the easiest way is to use a polyfill.

The other possible approach is that we could have a transformation that switches builtins to instead use a module (eg. replace `new Set` with `new require('core-js/library/fn/set')`) and bundle the implementation inside babili-standalone. That adds extra bytes though, and all other code that uses ES6 Sets will also have the same issue. It's easiest to just polyfill in your environment :)

**Comment by fatcerberus** [comment]
Well, for what it's worth, the polyfill worked and my compiler can do automated minification now.  So thanks again! 😄 

Since the whole reason I added Babel was in order to support ES6+ code in the first place, the polyfill is a welcome addition to my environment anyway.

**Comment by Daniel15** [comment]
Glad to hear that it worked! I'm going to close this issue, but let us know if you have any other questions! 😃
