### ISSUE TITLE
Auto-update script doesn't handle UTF-8 characters correctly

### ISSUE THREAD

**Issue by fatcerberus** [babel/babel-standalone#76]
At first I thought this was a bug in my JS runtime, but the minified script doesn't parse in Node either.

```
C:\Users\fatce\Desktop>node babel.min.js
C:\Users\fatce\Desktop\babel.min.js:6
},e.prototype.setData=function(e,t){return this.data[e]=t},e.prototype.getData=function(e){var t=this;do{var r=t.data[e];if(null!=r)return r}while(t=t.parent)},e.prototype.removeData=function(e){var t=this;do{var r=t.data[e];null!=r&&(t.data[e]=null)}while(t=t.parent)},e.prototype.init=function(){this.references||this.crawl()},e.prototype.crawl=function(){M++,this._crawl(),M--},e.prototype._crawl=function(){var e=this.path;if(this.references=(0,c.default)(null),this.bindings=(0,c.default)(null),this.globals=(0,c.default)(null),this.uids=(0,c.default)(null),this.data=(0,c.default)(null),e.isLoop())for(var t=R.FOR_INIT_KEYS,r=Array.isArray(t),n=0,t=r?t:(0,v.default)(t);;){var i;if(r){if(n>=t.length)break;i=t[n++]}else{if(n=t.next(),n.done)break;i=n.value}var s=i,a=e.get(s);a.isBlockScoped()&&this.registerBinding(a.node.kind,a)}if(e.isFunctionExpression()&&e.has("id")&&(e.get("id").node[R.NOT_LOCAL_BINDING]||this.registerBinding("local",e.get("id"),e)),e.isClassExpression(
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

The unminified script is fine.

**Comment by Daniel15** [comment]
Hmm strange, the minified version should just be the unminified version after running it through UglifyJS. I'll take a look!

Have you seen this in any older versions of babel-standalone, or just the latest version?

**Comment by fatcerberus** [comment]
I didn't check the older versions, only the latest release on GitHub (6.21.1).

**Comment by fatcerberus** [comment]
@Daniel15 Any luck figuring this out?

**Comment by loganfsmyth** [comment]
So if you run this on your own machine it errors? For me I get:

```
$ node -v
v0.10.48
$ npm i babel-standalone
babel-standalone@6.21.1 node_modules/babel-standalone
$ nvm use 0.10
Now using node v0.10.48 (npm v2.15.1)
$ node node_modules/babel-standalone/babel.min.js
```

So no errors on my side.

**Comment by fatcerberus** [comment]
Huh, you're right, when installed through npm it's fine.  But using the `babel.min.js` from the Releases page:
https://github.com/babel/babel-standalone/releases/tag/release-6.21.1

I get the error posted above.

**Comment by loganfsmyth** [comment]
@Daniel15 Must be an encoding issue with your release creation scripts. I don't know Powershell though, so hard to help more. The release file definitely isn't UTF8.

**Comment by Daniel15** [comment]
Sorry about that! I tried to fix it, but my fix didn't work, so I've just manually attached valid files for the 6.22.1 release. I'll take a closer look and see what's happening. My script is calling GitHub's API to attach the build artifacts to the release. I think I need to somehow specify the content-type in the GitHub API request itself.

**Comment by fatcerberus** [comment]
Thanks, good to know I'm not going crazy.
