### ISSUE TITLE
New build breaks text/babel and text/jsx fetching

### ISSUE THREAD

**Issue by tomgillespy** [babel/babel-standalone#84]
I can't get a test case just yet, but the new release fetched from the cdn broke fetching of javascript using text/babel and text/jsx in the type descriptor. I've downgraded to 6.24.0 and it works fine again.

I have the babel script in the head:
`<script src="assets/custom/js/babel.min.js" charset="utf8"></script>`

And below in the document 'footer' I have my assets, one of them includes
`<script type="text/babel" src="assets/custom/js/haversine.babel.js"></script>`

And it was not fetching the haversine script to transpile it.

I should be able to get a better test case later today.

**Comment by RRSprinkhuizen** [comment]
Behaviour and workaround confirmed by me :-p Thanks.

**Comment by Daniel15** [comment]
Thanks for the bug report! Looking...

**Comment by Daniel15** [comment]
Thanks for reporting this! I've patched this in 6.24.2 release and have confirmed it's working correctly now: https://babel-standalone.dan.cx/examples/scriptTag-src.htm
