### ISSUE TITLE
Can you export buildExternalHelpers for rollup-babel-standalone ?

### ISSUE THREAD

**Issue by jetiny** [babel/babel-standalone#87]
```
export const availablePlugins = {};
export const availablePresets = {};
// export buildExternalHelpers
export const buildExternalHelpers = Babel.buildExternalHelpers;
```

**Comment by Daniel15** [comment]
What is "rollup-babel-standalone"?

This should be easy to do, feel free to send a pull request.

**Comment by jetiny** [comment]
Thanks.
[rollup website](rollupjs.org)

**Comment by loganfsmyth** [comment]
This seems like a reasonable thing to expose. The question above isn't asking what Rollup is, it's asking how that ties to standalone. I don't get how you'd combine Rollup and babel-standalone. The point of `babel-standalone` is non-Node usage, and Rollup is entirely Node.

**Comment by jetiny** [comment]
It's for node only, For some reasons we need to use babel-standalone with rollup-plugin-babel, but it need [buildExternalHelpers](https://github.com/jetiny/rollup-plugin-babel-standalone/commit/6d8d57eab2a86a2c3c638054d5d39793cb2475ba#diff-1fdf421c05c1140f6d71444ea2b27638)

**Comment by Daniel15** [comment]
Added in #88

**Comment by loganfsmyth** [comment]
@jetiny There's no benefit to using `babel-standalone` with Rollup. If you're finding that necessary, I'd recommend exploring why that is, since you're now reinventing existing tooling for Rollup.

**Comment by jetiny** [comment]
Out CI is too slow, even if we use yarn and a private cnpm registry, we must cut down the dependencies of npm packages
