### ISSUE TITLE
Include "idx" plugin

### ISSUE THREAD

**Issue by Daniel15** [babel/babel-standalone#89]
https://github.com/facebookincubator/idx

**Comment by xtuc** [comment]
Could we use https://github.com/babel/babel/pull/5813 instead? It's in the 7 branch.

**Comment by Daniel15** [comment]
@xtuc - Oh cool, I didn't realise that proposal even existed! Is that pull request just a syntax plugin, or does it also contain the transform?

**Comment by xtuc** [comment]
It contains the transformation and the syntax plugin. Babylon must be updated as well.

**Comment by hzoo** [comment]
https://github.com/babel/babel/releases/tag/v7.0.0-alpha.15, yeah it would be great if we could have 7.x alpha automatically published separately

**Comment by Daniel15** [comment]
Not relevant any more.
